sudo: false
language: node_js
node_js:
  - "6"
branches:
  only:
  - master
script: npm run build
after_success:
- git add lib
- git commit -m 'Add compiled javascript sources'
- git push --force --quiet https://$GH_TOKEN@github.com/kumabook/kumagorithm.git HEAD:gh-pages
  2> /dev/null
env:
  global:
  - GIT_COMMITTER_NAME=Hiroki Kumamoto
  - GIT_COMMITTER_EMAIL=kumabook@live.jp
  - GIT_AUTHOR_NAME=Hiroki Kumamoto
  - GIT_AUTHOR_EMAIL=kumabook@live.jp
  - secure: "vYAebXgDyqK9e4Q/C05BkVxddkfxhmLUOeH0dp3ceHsD7lcZaHeABN53AeDFrxScYlYIQCgNpYhRKQ5JWweqRmg9YCO6gzlB8CWYekQbv3SuFghPOWE0o/aptewLrOl5UvacY4Z10Nbw/moHAgQdA+GIM/z1F8+5YkmdC8c+SzM="
