sudo: false
language: node_js
node_js:
  - '0.10'
branches:
  only:
    - travis_dev

before_script:
  - git clone --quiet https://github.com/kumabook/kumagorithm.git build
  - pushd build
  - git checkout -b gh-pages
  - popd

script: node_modules/gulp/bin/gulp.js webpack

after_success:
  - cd build
  - git add -A
  - git commit -m 'Update'
  - 'git push --quiet https://$GH_TOKEN@github.com/kumabook/kumagorithm.git gh-pages 2> /dev/null'

env:
 global:
   - GIT_COMMITTER_NAME=Hiroki Kumamoto
   - GIT_COMMITTER_EMAIL=kumabook@live.jp
   - GIT_AUTHOR_NAME=Hiroki Kumamoto
   - GIT_AUTHOR_EMAIL=kumabook@live.jp

secure: "sYWslsDygebFijF6w3ULRcZ33LcGiTZrsP1m0LyB/YN9yVEF7y07atZ3j65raEgIPpxAUzRrafTf8xvxBNXPM52bSAv4D+Ob0Dm4QhRyz6dy1d0myUgbo7ShgF0SDtfcscSs2QPm0GlNwnOlacrD3NXzzqGhav8ToCibjN2Mtsk="